title: HelloWorld!<>
email: aaronsms@u.nus.edu

header_pages: 
  - developer_guide.md
  - about.md
 
url: "https://aaronsms.github.io/HelloWorld/"

# Build settings
theme: minima
plugins:
  - jekyll-feed
