name: helloworld
description: A platform for all language learners.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.1
  freezed_annotation: ^0.7.1
  provider: ^4.1.2
  flutter_bloc: ^4.0.0
  image_picker: ^0.6.7+1
  postgres: ^2.1.1
  dropdownfield: ^1.0.0
  url_launcher: ^5.4.10
  pin_code_fields: ^3.0.1
  google_sign_in: ^4.5.1
  path: ^1.7.0
  get_it: ^4.0.2
  injectable: ^0.4.0+1

dev_dependencies:
  build_runner:
  freezed: ^0.10.9
  injectable_generator: ^0.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/learner_step2.png
    - assets/images/learner_step1.png
    - assets/images/mentor_step1.png
    - assets/images/mentor_step2.png
    - assets/images/mentor_step3.png
    - assets/images/verifyemail.png
    - assets/images/verifiedemail.png
    - assets/images/applicationmentor.png

  fonts:
    - family: Gill Sans
      fonts:
        - asset: fonts/gillsans.ttf

    - family: Martel Sans
      fonts:
        - asset: fonts/MartelSans-Black.ttf
          weight: 900
        - asset: fonts/MartelSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/MartelSans-Bold.ttf
          weight: 700
        - asset: fonts/MartelSans-SemiBold.ttf
          weight: 600
        - asset: fonts/MartelSans-Regular.ttf
          weight: 400
        - asset: fonts/MartelSans-Light.ttf
          weight: 300
        - asset: fonts/MartelSans-ExtraLight.ttf
          weight: 200
