name: helloworld
description: A platform for all language learners.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.1
  freezed_annotation: ^0.7.1
  provider: ^4.1.2
  pin_code_fields: ^3.0.1
  flutter_bloc: ^4.0.0
  postgres: ^2.1.1
  google_sign_in: ^4.5.1
  path: ^1.7.0
  get_it: ^4.0.2
  injectable: ^0.4.0+1
  uuid: ^2.0.4

dev_dependencies:
  build_runner:
  freezed: ^0.10.9
  injectable_generator: ^0.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/previewbar1.png
    - assets/images/previewbar2.png
    - assets/images/previewbar3.png
    - assets/images/hirepreview.png
    - assets/images/bookingpreview.png
    - assets/images/messengerpreview.png
    - assets/images/logo.png
    - assets/images/password_reset.png

  fonts:
    - family: Gill Sans
      fonts:
        - asset: fonts/gillsans.ttf
