name: helloworld
description: A platform for all language learners.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.1
  freezed_annotation: ^0.7.1
  provider: ^4.1.2
  flutter_bloc: ^4.0.0
  postgres: ^2.1.1
  google_sign_in: ^4.5.1
  path: ^1.7.0
  get_it: ^4.0.2
  injectable: ^0.4.0+1

dev_dependencies:
  build_runner:
  freezed: ^0.10.9
  injectable_generator: ^0.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/learner_step2.png
    - assets/images/learner_step1.png
    - assets/images/mentor_step1.png
    - assets/images/mentor_step2.png
    - assets/images/mentor_step3.png

  fonts:
    - family: Gill Sans
      fonts:
        - asset: fonts/gillsans.ttf
